version: "3.3"
services:
  db:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db-data:/var/lib/mysql/
    restart: always
    environment:
      TZ: America/Argentina/Buenos_Aires
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: deliwiz
      MYSQL_USER: deliwizback
      MYSQL_PASSWORD: deli123
    ports:
      - 3306:3306
    networks:
      - net

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:5
    restart: always
    ports:
      - 8083:80
    environment:
      PMA_HOST: db
    networks:
      - net

networks:
  net:
    driver: bridge
